TARGET = geometry
CC = gcc
CFLAGS = -Wall -Wextra -Werror
DEBAGFLAGS = -g3 -O0
DIRECTORIFLAGS = -I src

PREF_SRC_GEOMETRY = ./src/geometry/
PREF_SRC_LIBGEOMETRY = ./src/libgeometry/
PREF_OBJ_GEOMETRY = ./obj/src/geometry/
PREF_OBJ_LIBGEOMETRY = ./obj/src/libgeometry/
PREF_BIN = ./bin/

SRC_GEOMETRY = $(wildcard $(PREF_SRC_GEOMETRY)*.c)
SRC_LIBGEOMETRY = $(wildcard $(PREF_SRC_LIBGEOMETRY)*.c)

OBJ_GEOMETRY = $(patsubst $(PREF_SRC_GEOMETRY)%.c, $(PREF_OBJ_GEOMETRY)%.o, $(SRC_GEOMETRY))
OBJ_LIBGEOMETRY = $(patsubst $(PREF_SRC_LIBGEOMETRY)%.c, $(PREF_OBJ_LIBGEOMETRY)%.o, $(SRC_LIBGEOMETRY))

$(PREF_BIN)$(TARGET) : $(OBJ_GEOMETRY) $(PREF_OBJ_LIBGEOMETRY)libgeometry.a
	$(CC) $(CFLAGS) $(DIRECTORIFLAGS) $(OBJ_GEOMETRY) $(PREF_OBJ_LIBGEOMETRY)libgeometry.a -o $(PREF_BIN)$(TARGET) -lm

$(PREF_OBJ_GEOMETRY)%.o : $(PREF_SRC_GEOMETRY)%.c
	$(CC) $(CFLAGS) $(DIRECTORIFLAGS) -c $< -o $@

$(PREF_OBJ_LIBGEOMETRY)libgeometry.a : $(OBJ_LIBGEOMETRY)
	ar rcs $@ $^

$(PREF_OBJ_LIBGEOMETRY)%.o : $(PREF_SRC_LIBGEOMETRY)%.c
	$(CC) $(CFLAGS) $(DIRECTORIFLAGS) -c $< -o $@

run :
	$(PREF_BIN)$(TARGET)
.PHONY : clean
clean :
	rm $(PREF_BIN)$(TARGET) $(PREF_OBJ_GEOMETRY)*.o $(PREF_OBJ_LIBGEOMETRY)*.o $(PREF_OBJ_LIBGEOMETRY)*.a
